import {Platform, StyleSheet} from 'react-native';
import {colors} from '../../assets/colors';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: 'white'},
  carouselContainer: {
    height: 350,
    width: '100%',
    marginTop: 20,
    // marginBottom: 10,
  },
  infoContainer: {
    height: '40%',
    width: '100%',
    // paddingTop: 15,
    // paddingHorizontal: 15,
    gap: 30,
    // marginTop: 10,
  },
  innerInfo: {
    gap: 10,
    backgroundColor: 'white',
    shadowColor: '#ccc',
    shadowOpacity: 0.5,
    shadowRadius: 2,
    shadowOffset: {height: 5, width: 0},
    elevation: 15,
    paddingHorizontal: 20,
    borderEndStartRadius: 30,
    borderEndEndRadius: 30,
    borderBottomLeftRadius: Platform.OS === 'android' ? 30 : undefined,
    borderBottomRightRadius: Platform.OS === 'android' ? 30 : undefined,
    paddingTop: 30,
    paddingBottom: 15,
    overflow: Platform.OS === 'android' ? 'hidden' : 'visible',
  },
  visual: {flexDirection: 'row', justifyContent: 'space-between'},
  producer: {
    fontSize: 20,
    color: colors.PLATINUM_GRAY,
  },
  nameText: {
    fontSize: 24,
    color: colors.RICH_BLACK,
  },
  costText: {
    fontSize: 20,
    color: colors.RICH_BLACK,
  },
  descriptionText: {
    fontSize: 16,
    color: colors.PLATINUM_GRAY,
  },
  cartButtonStyle: {
    backgroundColor: colors.VIVID_GAMBOGE,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    minHeight: 30,
    minWidth: 50,
    maxHeight: 60,
    maxWidth: 400,
    height: 50,
    width: '100%',
  },
  buttonsContainer: {
    // paddingTop: 30,
    paddingHorizontal: 20,
    gap: 15,
  },
  contentStyle: {
    // gap: 20,
    // paddingVertical: 10,
    // marginHorizontal: 20,
  },
  wrapperStyle: {
    flex: 1,
    justifyContent: 'space-between',
  },
  seeMoreStyle: {color: colors.VIVID_GAMBOGE},
  seeLessStyle: {color: colors.MIDNIGHT},
  similar: {paddingHorizontal: 20, gap: 10},
  back: {
    position: 'absolute',
    top: 20,
    left: 20,
    zIndex: 1,
    height: 35,
    width: 35,
    borderRadius: 30,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',

    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  imageStyle: {
    height: '100%',
    width: '100%',
    // resizeMode: 'center',
  },
});
